plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: BDHU/minimalist
title: Creative Coding Spring 2024 Online
description: The website for Creative Coding Spring 2024 Online

sidebar:
  - name: Home Page
    link: ./
  - name: Sample
    link: ./another-page.html
