plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

remote_theme: BDHU/minimalist
title: Creative Coding Spring 2024 Online
description: The website for Creative Coding Spring 2024 Online

sidebar:
  - name: Home Page (syllabus)
    link: ./
  - name: Week 01 - Intro to Creative Coding and p5js
    link: ./week1
  - name: Week 02 - Forms, Shapes and Variables
    link: ./week2
  - name: Week 03 - Computational Color and Export
    link: ./week2
